/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package cloudbase.core.master.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import com.facebook.thrift.*;

import com.facebook.thrift.protocol.*;
import com.facebook.thrift.transport.*;

public class TableDeletionException extends Exception implements TBase, java.io.Serializable {
  public String table;
  public boolean exists;

  public final Isset __isset = new Isset();
  public static final class Isset implements java.io.Serializable {
    public boolean table = false;
    public boolean exists = false;
  }

  public TableDeletionException() {
  }

  public TableDeletionException(
    String table,
    boolean exists)
  {
    this();
    this.table = table;
    this.__isset.table = true;
    this.exists = exists;
    this.__isset.exists = true;
  }

  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TableDeletionException)
      return this.equals((TableDeletionException)that);
    return false;
  }

  public boolean equals(TableDeletionException that) {
    if (that == null)
      return false;

    boolean this_present_table = true && (this.table != null);
    boolean that_present_table = true && (that.table != null);
    if (this_present_table || that_present_table) {
      if (!(this_present_table && that_present_table))
        return false;
      if (!this.table.equals(that.table))
        return false;
    }

    boolean this_present_exists = true;
    boolean that_present_exists = true;
    if (this_present_exists || that_present_exists) {
      if (!(this_present_exists && that_present_exists))
        return false;
      if (this.exists != that.exists)
        return false;
    }

    return true;
  }

  public int hashCode() {
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case 1:
          if (field.type == TType.STRING) {
            this.table = iprot.readString();
            this.__isset.table = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2:
          if (field.type == TType.BOOL) {
            this.exists = iprot.readBool();
            this.__isset.exists = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();
  }

  public void write(TProtocol oprot) throws TException {
    TStruct struct = new TStruct("TableDeletionException");
    oprot.writeStructBegin(struct);
    TField field = new TField();
    if (this.table != null) {
      field.name = "table";
      field.type = TType.STRING;
      field.id = 1;
      oprot.writeFieldBegin(field);
      oprot.writeString(this.table);
      oprot.writeFieldEnd();
    }
    field.name = "exists";
    field.type = TType.BOOL;
    field.id = 2;
    oprot.writeFieldBegin(field);
    oprot.writeBool(this.exists);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  public String toString() {
    StringBuilder sb = new StringBuilder("TableDeletionException(");
    sb.append("table:");
    sb.append(this.table);
    sb.append(",exists:");
    sb.append(this.exists);
    sb.append(")");
    return sb.toString();
  }

}

