/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package cloudbase.core.tabletserver.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import com.facebook.thrift.*;

import com.facebook.thrift.protocol.*;
import com.facebook.thrift.transport.*;

public class ConstraintViolationException extends Exception implements TBase, java.io.Serializable {
  public List<cloudbase.core.data.ConstraintViolationSummary> violationSummaries;

  public final Isset __isset = new Isset();
  public static final class Isset implements java.io.Serializable {
    public boolean violationSummaries = false;
  }

  public ConstraintViolationException() {
  }

  public ConstraintViolationException(
    List<cloudbase.core.data.ConstraintViolationSummary> violationSummaries)
  {
    this();
    this.violationSummaries = violationSummaries;
    this.__isset.violationSummaries = true;
  }

  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ConstraintViolationException)
      return this.equals((ConstraintViolationException)that);
    return false;
  }

  public boolean equals(ConstraintViolationException that) {
    if (that == null)
      return false;

    boolean this_present_violationSummaries = true && (this.violationSummaries != null);
    boolean that_present_violationSummaries = true && (that.violationSummaries != null);
    if (this_present_violationSummaries || that_present_violationSummaries) {
      if (!(this_present_violationSummaries && that_present_violationSummaries))
        return false;
      if (!this.violationSummaries.equals(that.violationSummaries))
        return false;
    }

    return true;
  }

  public int hashCode() {
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case 1:
          if (field.type == TType.LIST) {
            {
              TList _list0 = iprot.readListBegin();
              this.violationSummaries = new ArrayList<cloudbase.core.data.ConstraintViolationSummary>(_list0.size);
              for (int _i1 = 0; _i1 < _list0.size; ++_i1)
              {
                cloudbase.core.data.ConstraintViolationSummary _elem2 = new cloudbase.core.data.ConstraintViolationSummary();
                _elem2 = new cloudbase.core.data.ConstraintViolationSummary();
                _elem2.read(iprot);
                this.violationSummaries.add(_elem2);
              }
              iprot.readListEnd();
            }
            this.__isset.violationSummaries = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();
  }

  public void write(TProtocol oprot) throws TException {
    TStruct struct = new TStruct("ConstraintViolationException");
    oprot.writeStructBegin(struct);
    TField field = new TField();
    if (this.violationSummaries != null) {
      field.name = "violationSummaries";
      field.type = TType.LIST;
      field.id = 1;
      oprot.writeFieldBegin(field);
      {
        oprot.writeListBegin(new TList(TType.STRUCT, this.violationSummaries.size()));
        for (cloudbase.core.data.ConstraintViolationSummary _iter3 : this.violationSummaries)        {
          _iter3.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  public String toString() {
    StringBuilder sb = new StringBuilder("ConstraintViolationException(");
    sb.append("violationSummaries:");
    sb.append(this.violationSummaries);
    sb.append(")");
    return sb.toString();
  }

}

