javaaddpath({...
'/home/gridsan/kepner/SVN/d4m_api/lib/commons-logging-1.0.4.jar', ...
'/home/gridsan/kepner/SVN/d4m_api/lib/log4j-1.2.15.jar', ...
'/home/gridsan/kepner/SVN/d4m_api/lib/hadoop-0.19.0-core.jar', ...
'/home/gridsan/kepner/SVN/d4m_api/lib/hadoop-0.19.0-tools.jar', ...
'/home/gridsan/kepner/SVN/d4m_api/lib/thrift-20080411p1.jar', ...
'/home/gridsan/kepner/SVN/d4m_api/lib/zookeeper-3.2.0.jar', ...
'/home/gridsan/kepner/SVN/d4m_api/lib/cloudbase-core-1.0.0-RC2.jar', ...
'/home/gridsan/kepner/SVN/d4m_api/lib/d4m_api-0.01.jar', ...
});

%'/home/gridsan/kepner/SVN/d4m_api/conf/', ...

