function [Aout] = removeStopWords(A)
%removeStopWords Removes words from list of stopwords
%   Given an Associative Array with word columns, removes
%	stopwords from that Associative Array.

nl=char(10);

% List of stopwords
stopWords=['a''s' nl 'a' nl 'able' nl 'about' nl 'above' nl 'according' nl 'accordingly' nl 'across' nl 'actually' nl...
    'after' nl 'afterwards' nl 'again' nl 'against' nl 'ain''t' nl 'all' nl 'allow' nl 'allows' nl 'almost' nl 'alone' nl...
    'along' nl 'already' nl 'also' nl 'although' nl 'always' nl 'am' nl 'among' nl 'amongst' nl 'an' nl 'and' nl 'another' nl...
    'any' nl 'anybody' nl 'anyhow' nl 'anyone' nl 'anything' nl 'anyway' nl 'anyways' nl 'anywhere' nl 'apart' nl 'appear' nl...
    'appreciate' nl 'appropriate' nl 'are' nl 'aren''t' nl 'around' nl 'as' nl 'aside' nl 'ask' nl 'asking' nl 'associated' nl...
    'at' nl 'available' nl 'away' nl 'awfully' nl 'be' nl 'became' nl 'because' nl 'become' nl 'becomes' nl 'becoming' nl...
    'been' nl 'before' nl 'beforehand' nl 'behind' nl 'being' nl 'believe' nl 'below' nl 'beside' nl 'besides' nl 'best' nl...
    'better' nl 'between' nl 'beyond' nl 'both' nl 'brief' nl 'but' nl 'by' nl 'c''mon' nl 'c''s' nl 'came' nl 'can' nl...
    'can''t' nl 'cannot' nl 'cant' nl 'cause' nl 'causes' nl 'certain' nl 'certainly' nl 'changes' nl 'clearly' nl 'co' nl...
    'com' nl 'come' nl 'comes' nl 'concerning' nl 'consequently' nl 'consider' nl 'considering' nl 'contain' nl 'containing' nl...
    'contains' nl 'corresponding' nl 'could' nl 'couldn''t' nl 'course' nl 'currently' nl 'definitely' nl 'described' nl...
    'despite' nl 'did' nl 'didn''t' nl 'different' nl 'do' nl 'does' nl 'doesn''t' nl 'doing' nl 'don''t' nl 'done' nl 'down' nl...
    'downwards' nl 'during' nl 'each' nl 'edu' nl 'eg' nl 'eight' nl 'either' nl 'else' nl 'elsewhere' nl 'enough' nl...
    'entirely' nl 'especially' nl 'et' nl 'etc' nl 'even' nl 'ever' nl 'every' nl 'everybody' nl 'everyone' nl 'everything' nl...
    'everywhere' nl 'ex' nl 'exactly' nl 'example' nl 'except' nl 'far' nl 'few' nl 'fifth' nl 'first' nl 'five' nl 'followed' nl...
    'following' nl 'follows' nl 'for' nl 'former' nl 'formerly' nl 'forth' nl 'four' nl 'from' nl 'further' nl 'furthermore' nl...
    'get' nl 'gets' nl 'getting' nl 'given' nl 'gives' nl 'go' nl 'goes' nl 'going' nl 'gone' nl 'got' nl 'gotten' nl 'greetings' nl...
    'had' nl 'hadn''t' nl 'happens' nl 'hardly' nl 'has' nl 'hasn''t' nl 'have' nl 'haven''t' nl 'having' nl 'he' nl 'he''s' nl...
    'hello' nl 'help' nl 'hence' nl 'her' nl 'here' nl 'here''s' nl 'hereafter' nl 'hereby' nl 'herein' nl 'hereupon' nl 'hers' nl...
    'herself' nl 'hi' nl 'him' nl 'himself' nl 'his' nl 'hither' nl 'hopefully' nl 'how' nl 'howbeit' nl 'however' nl 'i''d' nl...
    'i''ll' nl 'i''m' nl 'i''ve' nl 'ie' nl 'if' nl 'ignored' nl 'immediate' nl 'in' nl 'inasmuch' nl 'inc' nl 'indeed' nl 'indicate' nl...
    'indicated' nl 'indicates' nl 'inner' nl 'insofar' nl 'instead' nl 'into' nl 'inward' nl 'is' nl 'isn''t' nl 'it' nl 'it''d' nl...
    'it''ll' nl 'it''s' nl 'its' nl 'itself' nl 'just' nl 'keep' nl 'keeps' nl 'kept' nl 'know' nl 'knows' nl 'known' nl 'last' nl...
    'lately' nl 'later' nl 'latter' nl 'latterly' nl 'least' nl 'less' nl 'lest' nl 'let' nl 'let''s' nl 'like' nl 'liked' nl...
    'likely' nl 'little' nl 'look' nl 'looking' nl 'looks' nl 'ltd' nl 'mainly' nl 'many' nl 'may' nl 'maybe' nl 'me' nl 'mean' nl...
    'meanwhile' nl 'merely' nl 'might' nl 'more' nl 'moreover' nl 'most' nl 'mostly' nl 'much' nl 'must' nl 'my' nl 'myself' nl...
    'name' nl 'namely' nl 'nd' nl 'near' nl 'nearly' nl 'necessary' nl 'need' nl 'needs' nl 'neither' nl 'never' nl 'nevertheless' nl...
    'new' nl 'next' nl 'nine' nl 'no' nl 'nobody' nl 'non' nl 'none' nl 'noone' nl 'nor' nl 'normally' nl 'not' nl 'nothing' nl...
    'novel' nl 'now' nl 'nowhere' nl 'obviously' nl 'of' nl 'off' nl 'often' nl 'oh' nl 'ok' nl 'okay' nl 'old' nl 'on' nl 'once' nl...
    'one' nl 'ones' nl 'only' nl 'onto' nl 'or' nl 'other' nl 'others' nl 'otherwise' nl 'ought' nl 'our' nl 'ours' nl 'ourselves' nl...
    'out' nl 'outside' nl 'over' nl 'overall' nl 'own' nl 'particular' nl 'particularly' nl 'per' nl 'perhaps' nl 'placed' nl 'please' nl...
    'plus' nl 'possible' nl 'presumably' nl 'probably' nl 'provides' nl 'que' nl 'quite' nl 'qv' nl 'rather' nl 'rd' nl 're' nl 'really' nl...
    'reasonably' nl 'regarding' nl 'regardless' nl 'regards' nl 'relatively' nl 'respectively' nl 'right' nl 'said' nl 'same' nl 'saw' nl...
    'say' nl 'saying' nl 'says' nl 'second' nl 'secondly' nl 'see' nl 'seeing' nl 'seem' nl 'seemed' nl 'seeming' nl 'seems' nl 'seen' nl...
    'self' nl 'selves' nl 'sensible' nl 'sent' nl 'serious' nl 'seriously' nl 'seven' nl 'several' nl 'shall' nl 'she' nl 'should' nl...
    'shouldn''t' nl 'since' nl 'six' nl 'so' nl 'some' nl 'somebody' nl 'somehow' nl 'someone' nl 'something' nl 'sometime' nl...
    'sometimes' nl 'somewhat' nl 'somewhere' nl 'soon' nl 'sorry' nl 'specified' nl 'specify' nl 'specifying' nl 'still' nl 'sub' nl...
    'such' nl 'sup' nl 'sure' nl 't''s' nl 'take' nl 'taken' nl 'tell' nl 'tends' nl 'th' nl 'than' nl 'thank' nl 'thanks' nl 'thanx' nl...
    'that' nl 'that''s' nl 'thats' nl 'the' nl 'their' nl 'theirs' nl 'them' nl 'themselves' nl 'then' nl 'thence' nl 'there' nl...
    'there''s' nl 'thereafter' nl 'thereby' nl 'therefore' nl 'therein' nl 'theres' nl 'thereupon' nl 'these' nl 'they' nl 'they''d' nl...
    'they''ll' nl 'they''re' nl 'they''ve' nl 'think' nl 'third' nl 'this' nl 'thorough' nl 'thoroughly' nl 'those' nl 'though' nl...
    'three' nl 'through' nl 'throughout' nl 'thru' nl 'thus' nl 'to' nl 'together' nl 'too' nl 'took' nl 'toward' nl 'towards' nl...
    'tried' nl 'tries' nl 'truly' nl 'try' nl 'trying' nl 'twice' nl 'two' nl 'un' nl 'under' nl 'unfortunately' nl 'unless' nl...
    'unlikely' nl 'until' nl 'unto' nl 'up' nl 'upon' nl 'us' nl 'use' nl 'used' nl 'useful' nl 'uses' nl 'using' nl 'usually' nl...
    'value' nl 'various' nl 'very' nl 'via' nl 'viz' nl 'vs' nl 'want' nl 'wants' nl 'was' nl 'wasn''t' nl 'way' nl 'we' nl 'we''d' nl...
    'we''ll' nl 'we''re' nl 'we''ve' nl 'welcome' nl 'well' nl 'went' nl 'were' nl 'weren''t' nl 'what' nl 'what''s' nl 'whatever' nl...
    'when' nl 'whence' nl 'whenever' nl 'where' nl 'where''s' nl 'whereafter' nl 'whereas' nl 'whereby' nl 'wherein' nl 'whereupon' nl...
    'wherever' nl 'whether' nl 'which' nl 'while' nl 'whither' nl 'who' nl 'who''s' nl 'whoever' nl 'whole' nl 'whom' nl 'whose' nl...
    'why' nl 'will' nl 'willing' nl 'wish' nl 'with' nl 'within' nl 'without' nl 'won''t' nl 'wonder' nl 'would' nl 'would' nl...
    'wouldn''t' nl 'yes' nl 'yet' nl 'you' nl 'you''d' nl 'you''ll' nl 'you''re' nl 'you''ve' nl 'your' nl 'yours' nl 'yourself' nl...
    'yourselves' nl 'zero' nl];


stopWords=CatStr(['word' nl],'|',stopWords);
Aout=A-A(:,stopWords); % Remove stopwords

end