/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package cloudbase.core.security.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import com.facebook.thrift.*;

import com.facebook.thrift.protocol.*;
import com.facebook.thrift.transport.*;

public class ThriftSecurityException extends Exception implements TBase, java.io.Serializable {
  public String user;
  public boolean baduserpass;

  public final Isset __isset = new Isset();
  public static final class Isset implements java.io.Serializable {
    public boolean user = false;
    public boolean baduserpass = false;
  }

  public ThriftSecurityException() {
  }

  public ThriftSecurityException(
    String user,
    boolean baduserpass)
  {
    this();
    this.user = user;
    this.__isset.user = true;
    this.baduserpass = baduserpass;
    this.__isset.baduserpass = true;
  }

  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ThriftSecurityException)
      return this.equals((ThriftSecurityException)that);
    return false;
  }

  public boolean equals(ThriftSecurityException that) {
    if (that == null)
      return false;

    boolean this_present_user = true && (this.user != null);
    boolean that_present_user = true && (that.user != null);
    if (this_present_user || that_present_user) {
      if (!(this_present_user && that_present_user))
        return false;
      if (!this.user.equals(that.user))
        return false;
    }

    boolean this_present_baduserpass = true;
    boolean that_present_baduserpass = true;
    if (this_present_baduserpass || that_present_baduserpass) {
      if (!(this_present_baduserpass && that_present_baduserpass))
        return false;
      if (this.baduserpass != that.baduserpass)
        return false;
    }

    return true;
  }

  public int hashCode() {
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case 1:
          if (field.type == TType.STRING) {
            this.user = iprot.readString();
            this.__isset.user = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2:
          if (field.type == TType.BOOL) {
            this.baduserpass = iprot.readBool();
            this.__isset.baduserpass = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();
  }

  public void write(TProtocol oprot) throws TException {
    TStruct struct = new TStruct("ThriftSecurityException");
    oprot.writeStructBegin(struct);
    TField field = new TField();
    if (this.user != null) {
      field.name = "user";
      field.type = TType.STRING;
      field.id = 1;
      oprot.writeFieldBegin(field);
      oprot.writeString(this.user);
      oprot.writeFieldEnd();
    }
    field.name = "baduserpass";
    field.type = TType.BOOL;
    field.id = 2;
    oprot.writeFieldBegin(field);
    oprot.writeBool(this.baduserpass);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  public String toString() {
    StringBuilder sb = new StringBuilder("ThriftSecurityException(");
    sb.append("user:");
    sb.append(this.user);
    sb.append(",baduserpass:");
    sb.append(this.baduserpass);
    sb.append(")");
    return sb.toString();
  }

}

